### PR TITLE
fix(MongoBinary): improve code

### LINKED ISSUE #373: For What is the function "MongoBinary.hasValidBinPath"
## Versions

package: mongo-memory-server-core

## What is your question?

What purpose does the function `MongoBinary.hasValidBinPath` have? it isnt used anywhere (and not tested)
https://github.com/nodkz/mongodb-memory-server/blob/82606d8ade8e3532cfeb867c0c262cab54dd2949/packages/mongodb-memory-server-core/src/util/MongoBinary.ts#L174-L181

and if not serving a purpose anymore, could we remove it (/ deprecated it)?

### PR DESCRIPTION
**Pull request by hasezoey**
- add tsdoc to many functions
- getCachePath: remove being async
- getDownloadPath: change the times to be more understandable
- getDownloadPath: use "this.getCachePath" instead of "this.cache[]"
- getPath: remove unnecessary variables
- getPath: add an Error if "binaryPath" is still false-y
- improve debug logging

closes #373

### CODE REVIEW

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 1]
```diff
@@ -32,54 +32,65 @@ export interface MongoBinaryOpts {
...
 
     return binaryPath;
   }
 
-  static async getCachePath(version: string): Promise<string> {
+  /**
+   * Check if specified version already exists in the cache
+   * @param version The Version to check for
+   */
+  static getCachePath(version: string): string {
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:59]: changed this function to not being async anymore, because it never needed to be async

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 2]
```diff
@@ -32,54 +32,65 @@ export interface MongoBinaryOpts {
...
+    // wait to get a lock
     await new Promise((resolve, reject) => {
       LockFile.lock(
         lockfile,
         {
-          wait: 120000,
+          wait: 1000 * 12, // 120 seconds
           pollPeriod: 100,
-          stale: 110000,
+          stale: 1000 * 11, // 110 seconds
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:82]: changed these numbers to be something more understandable

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 3]
```diff
@@ -32,54 +32,65 @@ export interface MongoBinaryOpts {
...
-          }
+          return err ? reject(err) : resolve();
         }
       );
     });
 
-    // again check cache, maybe other instance resolve it
-    if (!this.cache[version]) {
+    // check cache if it got already added to the cache
+    if (!this.getCachePath(version)) {
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:93]: changed to use the function over `this.cache[]` directly, because thats what the function is for

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 4]
```diff
@@ -128,17 +146,16 @@ export default class MongoBinary {
       checkMD5: envToBool(resolveConfig('MD5_CHECK') ?? ''),
     };
 
+    /** Provided Options combined with the Default Options */
     const options = { ...defaultOptions, ...opts };
-    log(`MongoBinary options: ${JSON.stringify(options)}`);
-
-    const { version, systemBinary } = options;
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:134]: removed these because they were not changed after this and wasn't shortening much

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 5]
```diff
@@ -147,30 +164,40 @@ export default class MongoBinary {
...
+      binaryPath = this.getCachePath(options.version);
     }
 
     if (!binaryPath) {
       binaryPath = await this.getDownloadPath(options);
     }
 
-    log(`MongoBinary: Mongod binary path: ${binaryPath}`);
+    if (!binaryPath) {
+      throw new Error(
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:188]: added an Error for more security in returns (because all of the functions above can return an false-y value

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts [hunk 6]
```diff
@@ -147,30 +164,40 @@ export default class MongoBinary {
...
+
+    log(`MongoBinary: Mongod binary path: "${binaryPath}"`);
     return binaryPath;
   }
 
+  /**
+   * Purpose unkown, not used anywhere
+   * @param files Array of Strings
+   */
   static hasValidBinPath(files: string[]): boolean {
```
Comment (hasezoey) [inline packages/mongodb-memory-server-core/src/util/MongoBinary.ts:201]: still dont know what this function is for (#373)

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts (hunk 2 above)
Comment (nodkz) [reply packages/mongodb-memory-server-core/src/util/MongoBinary.ts:82]: I'll fix it 12 -> 120 in next commit

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts (hunk 4 above)
Comment (nodkz) [reply packages/mongodb-memory-server-core/src/util/MongoBinary.ts:134]: agreed

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts (hunk 6 above)
Comment (nodkz) [reply packages/mongodb-memory-server-core/src/util/MongoBinary.ts:204]: I removing this ;)
Some old code 🤗

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts (hunk 5 above)
Comment (nodkz) [reply packages/mongodb-memory-server-core/src/util/MongoBinary.ts:191]: 👍

File: packages/mongodb-memory-server-core/src/util/MongoBinary.ts (hunk 3 above)
Comment (nodkz) [reply packages/mongodb-memory-server-core/src/util/MongoBinary.ts:93]: nice

**Review by nodkz — COMMENTED** [review]
Amazing! Thanks!
There are two small misses with timers. I'll fix them 😉

**Comment by hasezoey** [comment]
thanks for your additions, added "closes" to close the related issue (about that function)

**Comment by nodkz** [comment]
Heh, first merge-commit 😅

@hasezoey thanks for all your improvements. Repo & code became 100 times better & clearer 👍

**Comment by hasezoey** [comment]
> Heh, first merge-commit 

so i guess it dosnt really matter anymore what to use :sweat_smile:
